# Generated by Django 4.0.5 on 2022-06-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7)),
                ('marca', models.CharField(max_length=12)),
                ('modelo', models.CharField(max_length=12)),
                ('year', models.IntegerField()),
                ('vin', models.CharField(max_length=17)),
                ('millas', models.IntegerField()),
                ('categoria', models.IntegerField()),
                ('locacion', models.IntegerField()),
                ('disponibilidad', models.BooleanField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registrar auto',
                'verbose_name_plural': 'Registrar autos',
            },
        ),
        migrations.CreateModel(
            name='unirmeRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=12)),
                ('modelo', models.CharField(max_length=12)),
                ('year', models.IntegerField()),
                ('millas', models.CharField(max_length=20)),
                ('locacion', models.CharField(max_length=25)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=10)),
                ('estado', models.CharField(choices=[('contactado', 'Contactado'), ('registroauto', 'Registro auto'), ('noInteresado', 'No esta interesado')], default='n/a', max_length=30)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Solicitud web',
                'verbose_name_plural': 'Solicitud web',
            },
        ),
    ]
